version: '2.1'

services:
  login_api:
    build: .
    image: login_api
    container_name: login_api
    volumes:
      - .:/login
    ports:
      - '8096:8096'
    command: |
      bash -c "
        login \
          -B localhost:8096 \
          -vv"
  redis:
    image: 'redis:latest'